amazon/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls', namespace='products')),
    path('sections/',include('sections.urls')),
    path('posts/',include('posts.urls')),
    path('accounts/',include('accounts.urls')),




] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from posts.views import (PostsList, PostDetails,PostUpdate,PostCreate,PostDelete) 
from django.contrib.auth.decorators import login_required


urlpatterns = [
    path('',PostsList.as_view(), name='posts.list'),
    path('<int:pk>', PostDetails.as_view(), name='posts.details'),
    path('<int:pk>/edit', PostUpdate.as_view(), name='posts.edit'),
    path('create', PostCreate.as_view(), name='posts.create'),
    path('<int:pk>/delete', login_required(PostDelete.as_view()), name='posts.delete'),


]

products/urls.py
from django.urls import path
from .views import Home ,contact_us ,about_us , product_detail ,delete ,search 
from .views import create_product ,edit_product 



app_name = 'products'


urlpatterns = [
    path('home/', Home , name='home'),
    path('contact_us/', contact_us, name='contact_us'),
    path('about_us/', about_us, name='about_us'),
    path('products/product_detail/<int:id>/', product_detail, name='product_detail'),
    path('product/<int:id>/delete', delete, name='delete'),
    path('search/' , search ,name="search" ),
    path('create_product/',create_product,name="create_product"),
    path('edit/<int:product_id>/', edit_product, name='edit_product'),

]

products/models.py
from django.db import models
from django.urls import reverse
from sections.models import Section
from django.contrib.auth.models import User




class Product(models.Model):
    name = models.CharField("Name", max_length=100, null=True)
    description = models.TextField("Description", null=True)
    price = models.DecimalField("Price", decimal_places=2, max_digits=8)
    image = models.ImageField(upload_to='products/images/' ,null=False , blank=False)
    # created_at = models.DateTimeField(auto_now_add=True)
    # updated_at = models.DateField(auto_now=True)
    section = models.ForeignKey(Section, on_delete=models.SET_NULL, null=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)







    def __str__(self):
        return self.name
    
    def get_show_url(self):
        return reverse('products:product_detail', args=[self.id])
        
    def get_delete_url(self):
        return reverse('products:delete', args=[self.id])
    
    def get_image_url(self):
        return f"../media/{self.image}"


    @classmethod
    def get_all_products(cls):
        return cls.objects.all()
    

products/forms.py
from django import forms
from .models import Product
from sections.models import Section

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description','price', 'image']

# class ProductForm(forms.Form):
#     name=forms.CharField()
#     description = forms.CharField()
#     price = forms.DecimalField("Price", decimal_places=2, max_digits=8)
#     image = forms.ImageField(upload_to='products/images/' ,null=False , blank=False)
#     section = forms.ModelChoiceField(
#         Section.get_all_sections(),required=False
#     )
class ProfileForm(forms.Form):
    first_name = forms.CharField(max_length=100, required=False)
    last_name = forms.CharField(max_length=100, required=False)

products/views.py
from telnetlib import LOGOUT
from django.http import HttpResponseBadRequest, HttpResponseForbidden
from django.shortcuts import render ,get_object_or_404 ,redirect
from django.urls import reverse
from .models import Product 
from sections.models import Section
from .forms import ProductForm, ProfileForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages







def contact_us(request):
    return render(request, 'products/contact_us.html')

def about_us(request):
    return render(request, 'products/about_us.html')


def product_detail(request, id):
    product = get_object_or_404(Product, pk=id)
    related_products = Product.objects.filter(section=product.section).exclude(id=id)
    

    return render(request, 'products/product_detail.html', {'product': product, 'related_products': related_products})



def Home(request):
    products = Product.objects.all().order_by('id')
    return render(request, 'products/homepage.html',context={"products":products})

# @login_required()
# def delete(request, id):
#     product = Product.objects.get(id=id)
#     product.delete()    
#     url = reverse('products:home')
#     return redirect(url)

@login_required
def delete(request, id):
    product = get_object_or_404(Product, id=id)

    # Check if the user is the owner of the product
    if product.created_by != request.user:
        return HttpResponseForbidden("You do not have permission to delete this product.")

    product.delete()
    url = reverse('products:home')
    return redirect(url)

def search(request):
    query = request.GET.get('q', '') 
    products = Product.objects.filter(name__icontains=query)  
    return render(request, 'products/search.html', {'products': products, 'query': query})
 
@login_required()
def create_product(request):
    sections = Section.objects.all()

    if request.method == 'POST':
        name = request.POST.get('name')
        price = request.POST.get('price')
        description = request.POST.get('description')
        image = request.FILES.get('image')

        if not name or not price:
            return render(request, 'products/create_product.html')

        try:
            price = float(price)
        except ValueError:
            return render(request, 'products/create_product.html')

        addProduct = Product()
        addProduct.name = name
        addProduct.price = price
        addProduct.description = description
        addProduct.image = image

        section_id = request.POST.get('section_id')
        if section_id:
            try:
                section = Section.objects.get(pk=section_id)
                addProduct.section = section
            except Section.DoesNotExist:
                return HttpResponseBadRequest("Invalid section ID")


        addProduct.created_by = request.user
        addProduct.save()

        url = reverse('products:product_detail', args=[addProduct.id])
        return redirect(url)
    else:
        return render(request, 'products/create_product.html', {'sections': sections})


# def create_product(request, section_id):
#     if request.method == 'POST':
#         form = ProductForm(request.POST, request.FILES)
#         if form.is_valid():
#             # Assuming your form includes fields for name, price, and description
#             name = form.cleaned_data['name']
#             price = form.cleaned_data['price']
#             description = form.cleaned_data['description']

#             # Create a new product and associate it with the section
#             product = Product(name=name, price=price, description=description, section_id=section_id)
#             product.save()

#             return redirect('products:product_detail', product.id)
#     else:
#         form = ProductForm()

#     return render(request, 'products/create_product.html', {'form': form})


# @login_required()
# def edit_product(request, product_id):
#     product = get_object_or_404(Product, pk=product_id)
#     if request.method == 'POST':
#         form = ProductForm(request.POST, request.FILES, instance=product)
#         if form.is_valid():
#             form.save()
#             return redirect('products:product_detail', product.id)
#     else:
#         form = ProductForm(instance=product)

#     return render(request, 'products/edit_product.html', {'form': form, 'product': product})

@login_required
def edit_product(request, product_id):
    product = get_object_or_404(Product, pk=product_id)

    # Check if the user is the owner of the product
    if product.created_by != request.user:
        return HttpResponseForbidden("You do not have permission to edit this product.")

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect('products:product_detail', product.id)
    else:
        form = ProductForm(instance=product)

    return render(request, 'products/edit_product.html', {'form': form, 'product': product})


@login_required
def profile_view(request):
    user = request.user  
    return render(request, 'profile.html', {'user': user})

@login_required
def edit_profile_view(request):
    user = request.user

    if request.method == 'POST':
        profile_form = ProfileForm(request.POST, instance=user.profile)
        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, 'Profile updated successfully.')
            return redirect('profile')
        else:
            messages.error(request, 'Profile update failed. Please correct the errors.')

    return render(request, 'edit_profile.html', {'user': user})

@login_required
def delete_profile_view(request):
    user = request.user

    if request.method == 'POST':
        user.delete()
        LOGOUT(request)
        messages.success(request, 'Your profile has been deleted successfully.')
        return redirect('login')

    return render(request, 'delete_profile.html', {'user': user})

products/templates/products/layouts/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>
        {%block Title%}
        {%endblock %}
    </title>
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <style></style>
</head>
<body>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Products</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarScroll">
        <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/products/home">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/products/contact_us">Contact US</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href='/products/about_us'>About Us</a>
          </li>
          {% if user.id %}
          <li class="nav-item mx-3">
            <a class="nav-link active{% if user.is_authenticated %} {% endif %}" href="/accounts/profile_view/">{% if user.is_authenticated %}{{ user }}{% else %}Guest{% endif %}</a>
        </li>
        
          <li class="nav-item mx-3">
            <a class="nav-link active" href="{% url "logout" %}">Logout</a>
          </li>
          
          {% else %}
          <li class="nav-item">
            <a class="nav-link active" href="{% url 'login' %}">Login</a>
          </li>
         <li class="nav-item mx-3">
            <a class="nav-link active" href="/accounts/register/" >Register</a>
          </li>  




          {% endif %}
        </ul>
        {% comment %} <form class="d-flex" role="search">
          <input class="form-control me-2" type="search"  placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" href="../search"  type="submit">Search</button>
        </form> {% endcomment %}
        <form class="d-flex" method="get" action="{% url 'products:search' %}" role="search">
          <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
        
      </div>
    </div>
</nav>

    
      <div class="container mt-4">
 



        <div class ="bg-warning text-danger text-center">
            {% block content %}

            {% endblock %}

        </div><br/>

        <div class=" ">
          {%block table%}

          {%endblock %}
        </div>
        {%block test%}

        {%endblock%}

        

    
    <footer class="footer">
        <div class="container fixed-bottom text-center">
            <p>&copy; {{ year }} Your Website Name</p>
        </div>
    </footer>
    
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>