amazon/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls', namespace='products')),
    path('sections/',include('sections.urls')),
    path('posts/',include('posts.urls')),
    path('accounts/',include('accounts.urls')),




] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from posts.views import (PostsList, PostDetails,PostUpdate,PostCreate,PostDelete) 
from django.contrib.auth.decorators import login_required


urlpatterns = [
    path('',PostsList.as_view(), name='posts.list'),
    path('<int:pk>', PostDetails.as_view(), name='posts.details'),
    path('<int:pk>/edit', PostUpdate.as_view(), name='posts.edit'),
    path('create', PostCreate.as_view(), name='posts.create'),
    path('<int:pk>/delete', login_required(PostDelete.as_view()), name='posts.delete'),


]

products/urls.py
from django.urls import path
from .views import Home ,contact_us ,about_us , product_detail ,delete ,search 
from .views import create_product ,edit_product 



app_name = 'products'


urlpatterns = [
    path('home/', Home , name='home'),
    path('contact_us/', contact_us, name='contact_us'),
    path('about_us/', about_us, name='about_us'),
    path('products/product_detail/<int:id>/', product_detail, name='product_detail'),
    path('product/<int:id>/delete', delete, name='delete'),
    path('search/' , search ,name="search" ),
    path('create_product/',create_product,name="create_product"),
    path('edit/<int:product_id>/', edit_product, name='edit_product'),

]

products/models.py
from django.db import models
from django.urls import reverse
from sections.models import Section
from django.contrib.auth.models import User




class Product(models.Model):
    name = models.CharField("Name", max_length=100, null=True)
    description = models.TextField("Description", null=True)
    price = models.DecimalField("Price", decimal_places=2, max_digits=8)
    image = models.ImageField(upload_to='products/images/' ,null=False , blank=False)
    # created_at = models.DateTimeField(auto_now_add=True)
    # updated_at = models.DateField(auto_now=True)
    section = models.ForeignKey(Section, on_delete=models.SET_NULL, null=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)







    def __str__(self):
        return self.name
    
    def get_show_url(self):
        return reverse('products:product_detail', args=[self.id])
        
    def get_delete_url(self):
        return reverse('products:delete', args=[self.id])
    
    def get_image_url(self):
        return f"../media/{self.image}"


    @classmethod
    def get_all_products(cls):
        return cls.objects.all()
    

products/forms.py
from django import forms
from .models import Product
from sections.models import Section

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description','price', 'image']

# class ProductForm(forms.Form):
#     name=forms.CharField()
#     description = forms.CharField()
#     price = forms.DecimalField("Price", decimal_places=2, max_digits=8)
#     image = forms.ImageField(upload_to='products/images/' ,null=False , blank=False)
#     section = forms.ModelChoiceField(
#         Section.get_all_sections(),required=False
#     )
class ProfileForm(forms.Form):
    first_name = forms.CharField(max_length=100, required=False)
    last_name = forms.CharField(max_length=100, required=False)

products/views.py
from telnetlib import LOGOUT
from django.http import HttpResponseBadRequest, HttpResponseForbidden
from django.shortcuts import render ,get_object_or_404 ,redirect
from django.urls import reverse
from .models import Product 
from sections.models import Section
from .forms import ProductForm, ProfileForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages







def contact_us(request):
    return render(request, 'products/contact_us.html')

def about_us(request):
    return render(request, 'products/about_us.html')


def product_detail(request, id):
    product = get_object_or_404(Product, pk=id)
    related_products = Product.objects.filter(section=product.section).exclude(id=id)
    

    return render(request, 'products/product_detail.html', {'product': product, 'related_products': related_products})



def Home(request):
    products = Product.objects.all().order_by('id')
    return render(request, 'products/homepage.html',context={"products":products})

# @login_required()
# def delete(request, id):
#     product = Product.objects.get(id=id)
#     product.delete()    
#     url = reverse('products:home')
#     return redirect(url)

@login_required
def delete(request, id):
    product = get_object_or_404(Product, id=id)

    # Check if the user is the owner of the product
    if product.created_by != request.user:
        return HttpResponseForbidden("You do not have permission to delete this product.")

    product.delete()
    url = reverse('products:home')
    return redirect(url)

def search(request):
    query = request.GET.get('q', '') 
    products = Product.objects.filter(name__icontains=query)  
    return render(request, 'products/search.html', {'products': products, 'query': query})
 
@login_required()
def create_product(request):
    sections = Section.objects.all()

    if request.method == 'POST':
        name = request.POST.get('name')
        price = request.POST.get('price')
        description = request.POST.get('description')
        image = request.FILES.get('image')

        if not name or not price:
            return render(request, 'products/create_product.html')

        try:
            price = float(price)
        except ValueError:
            return render(request, 'products/create_product.html')

        addProduct = Product()
        addProduct.name = name
        addProduct.price = price
        addProduct.description = description
        addProduct.image = image

        section_id = request.POST.get('section_id')
        if section_id:
            try:
                section = Section.objects.get(pk=section_id)
                addProduct.section = section
            except Section.DoesNotExist:
                return HttpResponseBadRequest("Invalid section ID")


        addProduct.created_by = request.user
        addProduct.save()

        url = reverse('products:product_detail', args=[addProduct.id])
        return redirect(url)
    else:
        return render(request, 'products/create_product.html', {'sections': sections})


# def create_product(request, section_id):
#     if request.method == 'POST':
#         form = ProductForm(request.POST, request.FILES)
#         if form.is_valid():
#             # Assuming your form includes fields for name, price, and description
#             name = form.cleaned_data['name']
#             price = form.cleaned_data['price']
#             description = form.cleaned_data['description']

#             # Create a new product and associate it with the section
#             product = Product(name=name, price=price, description=description, section_id=section_id)
#             product.save()

#             return redirect('products:product_detail', product.id)
#     else:
#         form = ProductForm()

#     return render(request, 'products/create_product.html', {'form': form})


# @login_required()
# def edit_product(request, product_id):
#     product = get_object_or_404(Product, pk=product_id)
#     if request.method == 'POST':
#         form = ProductForm(request.POST, request.FILES, instance=product)
#         if form.is_valid():
#             form.save()
#             return redirect('products:product_detail', product.id)
#     else:
#         form = ProductForm(instance=product)

#     return render(request, 'products/edit_product.html', {'form': form, 'product': product})

@login_required
def edit_product(request, product_id):
    product = get_object_or_404(Product, pk=product_id)

    # Check if the user is the owner of the product
    if product.created_by != request.user:
        return HttpResponseForbidden("You do not have permission to edit this product.")

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect('products:product_detail', product.id)
    else:
        form = ProductForm(instance=product)

    return render(request, 'products/edit_product.html', {'form': form, 'product': product})


@login_required
def profile_view(request):
    user = request.user  
    return render(request, 'profile.html', {'user': user})

@login_required
def edit_profile_view(request):
    user = request.user

    if request.method == 'POST':
        profile_form = ProfileForm(request.POST, instance=user.profile)
        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, 'Profile updated successfully.')
            return redirect('profile')
        else:
            messages.error(request, 'Profile update failed. Please correct the errors.')

    return render(request, 'edit_profile.html', {'user': user})

@login_required
def delete_profile_view(request):
    user = request.user

    if request.method == 'POST':
        user.delete()
        LOGOUT(request)
        messages.success(request, 'Your profile has been deleted successfully.')
        return redirect('login')

    return render(request, 'delete_profile.html', {'user': user})

products/templates/products/about_us.html
{% extends "products/layouts/base.html" %}
{% load static %}

{%block Title%}
About Page
{%endblock %}

{% block content %}
<h1>Welcome to the About Page</h1>
{% endblock %}

products/templates/products/contact_us.html
{% extends "products/layouts/base.html" %}

{% load static %}

{%block Title%}
contact_us
{%endblock %}


    {% block content %}
    <h1>Welcome to the Contact Page</h1>
    {% endblock %}

    {%block table%}
    <div class="container mt-5 w-25">
        <h2>Contact Us</h2>
        <form>
            <div class="form-group">
                <label for="name">Name:</label>
                <input type="text" class="form-control" id="name" placeholder="Enter your name" required>
            </div>
            <div class="form-group">
                <label for="email">Email:</label>
                <input type="email" class="form-control" id="email" placeholder="Enter your email" required>
            </div>
            <div class="form-group">
                <label for="message">Message:</label>
                <textarea class="form-control" id="message" rows="4" placeholder="Enter your message" required></textarea>
            </div>
            <button type="submit" class="btn btn-primary my-3">Submit</button>
        </form>
    </div>

    {%endblock%}

products/templates/products/create_product.html
{% extends "products/layouts/base.html" %}
{% load static %}

{% block Title %}
Create Product
{% endblock %}

{% block content %}
<h1>Welcome to the Create Product Page</h1>
{% endblock %}

{% block table %}
<h2>Create a New Product</h2>
<form method="post" enctype="multipart/form-data" class="form w-75 ">

    {% csrf_token %}

    <div class="form-group my-2">
        <label for="name">Name:</label>
        <input type="text" name="name" class="form-control" required>
    </div>

    <div class="form-group my-2">
        <label for="price">Price:</label>
        <input type="number" name="price" class="form-control" required>
    </div>

    <div class="form-group my-2">
        <label for="description">Description:</label>
        <textarea name="description" rows="4" cols="50" class="form-control"></textarea>
    </div>

    <div class="form-group my-2">
        <label for="section_id">Section:</label>
        <select name="section_id" class="form-control" required>
            <option value="" disabled selected>Select a Section</option>
            {% for section in sections %}
                <option value="{{ section.id }}">{{ section.name }}</option>
            {% endfor %}
        </select>
    </div>

    <div class="form-group my-2">
        <label for="image">Image:</label>
        <input type="file" name="image" accept="image/*" class="form-control" required>
    </div>

    <button type="submit" class="btn btn-primary">Create Product</button>
</form>
{% endblock %}

products/templates/products/edit_product.html
{% extends "products/layouts/base.html" %}
{% load static %}

{% block content %}
  <h1>Edit Product</h1>
{% endblock %}

{% block table %}
<div class="container">
    <form method="post" enctype="multipart/form-data" class="form">
        {% csrf_token %}

        <div class="form-group">
            {{ form.name.label_tag }}
            {{ form.name }}
        </div>

        <div class="form-group">
            {{ form.price.label_tag }}
            {{ form.price }}
        </div>

        <div class="form-group">
            {{ form.description.label_tag }}
            {{ form.description }}
        </div>

        <div class="form-group">
            {{ form.section_id.label_tag }}
            {{ form.section_id }}
        </div>

        <div class="form-group">
            {{ form.image.label_tag }}
            {{ form.image }}
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Save Changes</button>
            <a href="{% url 'products:home'  %}" class="btn btn-secondary">Cancel</a>
        </div>
    </form>
    
    <div class="mt-3">
        <a href="{% url 'products:product_detail' product.id %}" class="btn btn-info">View Product Details</a>
    </div>
</div>
{% endblock %}

products/templates/products/homepage.html
{% extends "products/layouts/base.html" %}
{% load static %}




{%block Title%}
Home
{%endblock %}

{% block content %}
<h1>This is Home Page</h1>
{% endblock %}
{% block table %}
<a href="{% url 'products:create_product'%}" class="btn btn-primary my-4">Add Product</a>

<table class="table container table-striped my-4 text-center">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Descriptions</th>
            <th>Price $</th>
            <th>Images</th>
            <th>Action</th>
            <th>Section</th>



        </tr>
    </thead>
    <tbody>
        {% for product in products %}
        <tr>
            <td>{{ product.id }}</td>
            <td>{{ product.name }}</td>
            <td>{{ product.description }}</td>
            <td>{{ product.price }}</td>
            <td>
                {% if product.image %}
                 <img src="{{ product.image.url }}" class="img-fluid" style="max-width: 110px;">
                {% else %}
                {% endif %}

            </td>                

            <td>
                {% comment %} <a href="{% url 'products:product_detail' product.id %}" class="btn btn-primary my-4">Details</a> {% endcomment %}
                <a href="{{product.get_show_url}}" class="btn btn-primary ">Details</a>
                <a href="{% url 'products:edit_product' product.id %}" class="btn btn-warning my-1">Edit</a>
                <a href="{{product.get_delete_url}}" class="btn btn-danger  ">Delete</a>
                {% comment %} <a href="{% url 'products:delete' product.id %}" class="btn btn-danger ">Delete</a> {% endcomment %}

            </td>
            <td>
                {% if product.section %}
                    {{ product.section.name }}
                {% else %}
                    No section assigned yet
                {% endif %}
            </td>   
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

products/templates/products/product_detail.html
 {% extends "products/layouts/base.html" %}
{% load static %}

{% block title %}Product Details{% endblock %}
{% block content %}
  <h1>Product Details</h1>
{% endblock %}

{% block table %}
<div class="container" style="display: flex; justify-content: space-between;">
  <div class="card text-center w-50 col-6 mx-4">
    <div class="card-body">
      <h5 class="card-title">{{ product.name }}</h5>
      <img src="{{ product.image.url }}" class="img-fluid" style="max-width: 400px;">
      <p class="card-text">{{ product.description }}</p>
      <p class="card-text">Price: ${{ product.price }}</p>
      
        {% comment %} <p class="card-text">Created by: {{ product.created_by.username }}</p> {% endcomment %}
        <p class="card-text">
          Created by:
          {% if product.created_by == request.user %}
            {{ product.created_by.username }}
          {% else %}
            Someone else
          {% endif %}
        </p>
                
      <a href="{% url 'products:home' %}" class="btn btn-primary my-4">Back Home</a>
    </div>
  </div>
  <div class="card  col-6 mx-3">
    <div class="card-body">
      <h2>Other Products in this section</h2>
      {% if product.section %}
        Section: {{ product.section.name }}
      {% else %}
        Section: No section assigned yet
      {% endif %}
      <ul>
        {% for related_product in related_products %}
          <li>
            <a href="{% url 'products:product_detail' related_product.id %}">{{ related_product.name }}</a>
          </li>
          
        {% endfor %}
        
      </ul>
    </div>
  </div>
</div>
{% endblock %}

products/templates/products/search.html
{% extends "products/layouts/base.html" %}
{% load static %}

{%block Title%}
Search Page
{%endblock %}

{% block content %}
<h1>Welcome to the Search Page</h1>

{% endblock %}

{% block table %}
<table class="table container table-striped text-center">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Descriptions</th>
            <th>Price $</th>
            <th>Images</th>
            <th>Action</th>



        </tr>
    </thead>
    <tbody>
        {% for product in products %}
        <tr>
            <td>{{ product.id }}</td>
            <td>{{ product.name }}</td>
            <td>{{ product.description }}</td>
            <td>{{ product.price }}</td>
            <td>
                <img src="{{ product.image.url }}" class="img-fluid" style="max-width: 110px;">
                {% comment %} <img src="{% static 'products/images/'|add:product.image %}" class="img-fluid" style="max-width: 400px;"> {% endcomment %}
            </td>                

            <td><br/>
                <a href="{% url 'products:product_detail' product.id %}" class="btn btn-primary my-4">Details</a>
                <a href="{% url 'products:delete' product.id %}" class="btn btn-danger ">Delete</a>

            </td>
   
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}